data_config:
    frame_len: 400
    frame_shift: 160
    seg_len: 60
    seg_shift: 60
    sequence_mode: True
    load_label: False
    use_iso_noise: False
    use_dir_noise: False
    use_reverb: False
    use_cmn: True
    snr_min: 10
    snr_max: 20
    t60_min: 0.1
    t60_max: 0.5
model_config:
    feat_dim: 80
    hidden_size: 512
    dropout: 0
    num_layers: 3
    label_size: 5768 
#    label_size: 4080
decoder_config:
    beam: 15
    lattice_beam: 8
    max_active: 7000
    acoustic_scale: 0.1 
