clean_source:
  1:    
    type: Librispeech
    wav: /datadisk2/lial/LibriSpeechWav/train-clean-100.zip
    label: /datadisk2/lial/LibriSpeechWav/train-clean-460-pdf-ids.txt
    aux_label: /datadisk2/lial/LibriSpeechWav/train-clean-460-trans-ids.txt
  2:
    type: Librispeech
    wav: /datadisk2/lial/LibriSpeechWav/train-clean-360.zip 
    aux_label: /datadisk2/lial/LibriSpeechWav/train-clean-460-trans-ids.txt
    label: /datadisk2/lial/LibriSpeechWav/train-clean-460-pdf-ids.txt
